export const environment = {
    baseUrl: 'http://localhost:9292/api',
    websocket: 'http://localhost:8090',
    indexClub: '/club',
    showClub: '/show',
    updateclub: '/club',
    showAsset: '/asset',
    showNews:'/news',
    showNew:'/new',
    file:'/file',
    rolTutor: 2,
    showSocios: '/socios',
    showSociosOfTutor: '/socios',
    showRols: '/rols',
    myProfile: '/my-profile',
    updateUser: '/user',
    showUser: '/user',
    allUsers: '/users',
    allUsersFaltas: '/obtener/usuarios',
    login: '/login',
    asignSocio: '/user/asign',
    removeSocio: '/user/remove',
    photo_profile_path:'photo_profile',
    landing_path:'landing',
    events_path:'events',
    news_path: 'news',
    getsPostEvento: '/eventos',
    getUpdateDeleteEvento: '/eventos/',
    getsPostCategorias: '/categorias',
    getUpdateDeleteCategorias: '/categorias/',
    getsNoSocios: '/noSocios',
    getPostUpdateDeleteNoSocios: '/noSocios/',
    postEventoUsuario: '/eventoUsuarios',
    getEventosVisibles: '/eventos/visibles',
    getComments: '/comments',
    rol_admin : 1,
    rol_redactor : 4,
    rol_tutor: 2,
    rol_webmaster:6,
    admin_card_image: '../../assets/cards-dashboard/_f85fcebc-e26f-4c23-97a8-7eefbbd9524c.jpg',
    redactor_card_image: '../../assets/cards-dashboard/_86275f07-3393-436b-bd61-2750bf845a4c.jpg',
    tutor_card_image: '../../assets/cards-dashboard/istockphoto-1345951925-640x640.jpg',
    indexContact: '/contact',
    getAllAlergias: '/alergias',
    showContact: '/contact',
    mail: '/mail',
    showAfinNews: '/afin-new',
    showRandNews:'/rand-new',
    showPopularNews: '/popular-news',
    showLatestNews: '/latest-news',
    counter: '/counter',
    recomend: '/summaries',
    fastReed: '/fast-reed',
    urlResetPass: '/forget-pass',
    getAllAlergiasOfUser: '/alergia-user'
};
