export const environment = {
    baseUrl: 'http://localhost:9292/api',
    websocket: 'http://localhost:8090',
    indexClub: '/club',
    showClub: '/show',
    updateclub: '/club',
    showAsset: '/asset',
    showNews:'/news',
    showNew:'/new',
    file:'/file',
    rolTutor: 2,
    showSocios: '/socios',
    showSociosOfTutor: '/socios',
    showRols: '/rols',
    myProfile: '/my-profile',
    updateUser: '/user',
    showUser: '/user',
    allUsers: '/users',
    allUsersFaltas: '/obtener/usuarios',
    login: '/login',
    asignSocio: '/user/asign',
    removeSocio: '/user/remove',
    photo_profile_path:'photo_profile',
    landing_path:'landing',
    getsPostEvento: '/eventos',
    getUpdateDeleteEvento: '/eventos/',
    getsPostCategorias: '/categorias',
    getUpdateDeleteCategorias: '/categorias/',
    getsNoSocios: '/noSocios',
    getPostUpdateDeleteNoSocios: '/noSocios/',
    postEventoUsuario: '/eventoUsuarios',
    getEventosVisibles: '/eventos/visibles'

};
